# Generated by Django 2.2.2 on 2019-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.TextField()),
                ('department', models.TextField()),
                ('level', models.TextField()),
                ('skills', models.TextField()),
                ('reference', models.TextField()),
            ],
        ),
    ]
