# Generated by Django 2.2.2 on 2019-08-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlXApp', '0002_auto_20190823_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='friend',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
